<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.3">
  <POU Name="MAIN_Shutdown" Id="{0b3b2413-2c53-4ea2-9d0c-46842e409463}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Shutdown
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Shutdown();]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Shutdown">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>