///////////////////////////////////////////////////////////////////////////////
// irSensorsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "irSensorsClassFactory.h"
#include "irSensorsServices.h"
#include "irSensorsVersion.h"
#include "updateIrSensors.h"

BEGIN_CLASS_MAP(CirSensorsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_irSensorsCupdateIrSensors, SRVNAME_IRSENSORS "!CupdateIrSensors", CupdateIrSensors)
///</AutoGeneratedContent>
END_CLASS_MAP()

CirSensorsClassFactory::CirSensorsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_IRSENSORS)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(irSensors));
#endif //defined(TCDBG_UNIT_VERSION)
}

