///////////////////////////////////////////////////////////////////////////////
// irSensorsInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "irSensorsServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
